### PR TITLE
bagfiles

### PR DESCRIPTION
**Pull request by MichaelrMentele**
Adds two bagfiles for the telekinesis goals topic:
* up/down
* left/right

# Recording
Run publish node like `ros2 run telekinesis publish_goals` in term 1

Then in term2 `ros2 record -a`

Do the motion using the controller. Close the recording.

# Testing
https://www.loom.com/share/a25e9e486b8843baa2e6621e7ddcd727?sid=74d279ed-0041-4994-abb7-8d4bf22ea71b

### CODE REVIEW

**Comment by MichaelrMentele** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/droidsx/droid-bodies/14?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#14** <a href="https://app.graphite.dev/github/pr/droidsx/droid-bodies/14?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#11** <a href="https://app.graphite.dev/github/pr/droidsx/droid-bodies/11?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#12** <a href="https://app.graphite.dev/github/pr/droidsx/droid-bodies/12?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MichaelrMentele and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MiguelSolisSegura — CHANGES_REQUESTED** [review]
sdd

**Comment by MiguelSolisSegura** [comment]
> > Mike, when I test the bags there seems to be a misalignment with the simulation and real robot setups. 
> > 
> > In ROS, Gazebo and recently as I discovered in Isaac Sim too, we usually utilize the following convention:
> > 
> > X+ Forward
> > Y+ Left
> > Z+ Up
> > 
> > When I tested the bag it seems that the Y+ is used as the Up axis. Can you confirm?
> 
> I believe that the most healty thing to do, is follow that convention for the telekinesis camera/phone setups that we create.

If you are curious, the way I actually tested that yesterday was by switching the coordinates in the MoveIt requests.

**Comment by MichaelrMentele** [comment]
Let me double check this in the AM. I think one of the axis may be inverted from what we would expect. I would need to re-record and repush.

**Comment by MichaelrMentele** [comment]
Are we good here can we merge?

**Comment by MichaelrMentele** [comment]
@MiguelSolisSegura good to land?

**Review by MiguelSolisSegura — APPROVED** [review]
The bags have been tested and movements in the arm correlate to the bag names. Approved.

**Pull request merged**
