### PR TITLE
Enable graphite support in WSL

### PR DESCRIPTION
**Pull request by MiguelSolisSegura**
### Summary

Added Homebrew and Graphite CLI installation to the development container.

### What changed?

The Dockerfile for the development container now includes steps to install Homebrew and the Graphite CLI. This is done using the official Homebrew installation script, followed by adding Homebrew to the PATH and installing the Graphite CLI using Homebrew.

### What to test?

1. Build the development container using the updated Dockerfile.
2. Ensure that your current Graphite workflow remains unaffected. This change is intended only for WSL users.

### Why this change is required?

This change enables Windows developers to use the Graphite CLI within the development container.

### CODE REVIEW

**Comment by MiguelSolisSegura** [comment]
* **#17** <a href="https://app.graphite.dev/github/pr/droidsx/droid-bodies/17?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MiguelSolisSegura and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MiguelSolisSegura** [comment]
### Merge activity

* **Sep 4, 2:59 PM EDT**: @MiguelSolisSegura merged this pull request with [Graphite](https://app.graphite.dev/github/pr/droidsx/droid-bodies/17).

**Review by MichaelrMentele — COMMENTED** [review]
I like the template for the PR -- feel free to add in the .github folder

**Review by MichaelrMentele — APPROVED** [review]
LGTM

**Pull request merged**
